spring:
    application:
        name: demo
server:
    port: 8080
        
---
spring:
    config:
        activate:
            on-profile: h2
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:travelplandb
        username: h2
        password: h2    
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:travelplandb
        username: prod
        password: prod    
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
---
spring:
    config:
        activate:
            on-profile: mysql
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/travel_plans
        username: root
        password: root 
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                format_sql: true
                
#spring.application.name=demo
#server.port=4042
##---
#spring.config.activate.on-profile=dev
##Datasouce Configuration pointing to H2 DB JDBC Connection
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:travelplandb
#spring.datasource.username=dev
#spring.datasource.password=dev
#
##ORM / JPA Properties (Optional for H2DB)
#spring.jpa.show-sql=true
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.format_sql=true
#
##---
#spring.config.activate.on-profile=prod
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:travelplandb
#spring.datasource.username=prod
#spring.datasource.password=prod
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.format_sql=true
##---
#spring.config.activate.on-profile=mysql
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#spring.datasource.username=root
#spring.datasource.password=Guruji123$
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
           